{
 "title": "Test stand",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Interval",
    "query": "15s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d"
   },
   {
    "name": "Blocks",
    "query": {
     "query": "label_values(zerg_proof_time_gauge, block_numbers)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Mem usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "test_process_proof_mem_gauge", "legendFormat": "Memory usage" }
   ]
  },
  {
   "title": "Current data info",
   "type": "logs",
   "gridPos": { "h": 23, "w": 10, "x": 14, "y": 0 },
   "targets": [
    { "expr": "test_mock_data_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Proof cost",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    { "expr": "test_proof_time_gauge_info", "legendFormat": "Block: {{label_name}}" }
   ]
  },
  {
   "title": "Proof time gen",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "test_proof_time_gauge_info", "legendFormat": "Block: {{label_name}}" }
   ]
  }
 ]
}